# Generated by Django 4.2.21 on 2025-07-06 22:22

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CulturalHighlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('address', models.TextField(blank=True)),
                ('website', models.URLField(blank=True)),
                ('image', models.URLField(blank=True)),
                ('cultural_tags', models.JSONField(default=list)),
                ('price_range', models.CharField(blank=True, max_length=20)),
                ('opening_hours', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('cultural_tags', models.JSONField(default=list)),
                ('music_scene', models.TextField(blank=True)),
                ('film_culture', models.TextField(blank=True)),
                ('culinary_highlights', models.TextField(blank=True)),
                ('cultural_activities', models.JSONField(default=list)),
                ('main_image', models.URLField(blank=True)),
                ('gallery_images', models.JSONField(default=list)),
                ('best_time_to_visit', models.CharField(blank=True, max_length=100)),
                ('average_cost', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Itinerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('planned', 'Planned'), ('completed', 'Completed')], default='draft', max_length=20)),
                ('cultural_match_score', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itineraries', to='users.destination')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itineraries', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ItineraryDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.IntegerField()),
                ('date', models.DateField()),
                ('title', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('itinerary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='users.itinerary')),
            ],
            options={
                'ordering': ['day_number'],
            },
        ),
        migrations.CreateModel(
            name='ItineraryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('order', models.IntegerField(default=0)),
                ('activity_type', models.CharField(choices=[('visit', 'Visit'), ('meal', 'Meal'), ('activity', 'Activity'), ('transport', 'Transport'), ('rest', 'Rest')], default='visit', max_length=20)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='users.itineraryday')),
                ('highlight', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.culturalhighlight')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CulturalProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('preferred_music_genres', models.JSONField(default=list)),
                ('preferred_film_genres', models.JSONField(default=list)),
                ('preferred_cuisine_types', models.JSONField(default=list)),
                ('preferred_activities', models.JSONField(default=list)),
                ('adventure_level', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('budget_level', models.CharField(choices=[('budget', 'Budget'), ('moderate', 'Moderate'), ('luxury', 'Luxury')], default='moderate', max_length=10)),
                ('travel_style', models.CharField(choices=[('relaxed', 'Relaxed'), ('active', 'Active'), ('cultural', 'Cultural'), ('adventure', 'Adventure'), ('luxury', 'Luxury')], default='cultural', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cultural_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='culturalhighlight',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highlights', to='users.destination'),
        ),
    ]
