# Generated by Django 5.2 on 2025-07-29 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_artiste_conseilculturel_oeuvre_playlist_evenement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conseilculturel',
            name='type',
            field=models.CharField(choices=[('domicile', 'At home'), ('voyage', 'While traveling')], max_length=20),
        ),
        migrations.AlterField(
            model_name='oeuvre',
            name='type',
            field=models.CharField(choices=[('film', 'Film'), ('musique', 'Music'), ('livre', 'Book'), ('recette', 'Recipe')], max_length=20),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='theme',
            field=models.CharField(choices=[('voyage', 'Travel'), ('soirée', 'Evening'), ('lecture', 'Reading'), ('découverte', 'Discovery'), ('autre', 'Other')], default='autre', max_length=50),
        ),
    ]
